### ISSUE TITLE
[BUG] Agent 安装失败：'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#587]
**问题描述**
Agent 安装失败：'NoneType' object has no attribute 'get'

**重现方法**
安装 Agent，非必现

```
Traceback (most recent call last):
  File "/data/bkee/bknodeman/nodeman/apps/utils/exc.py", line 71, in wrapped_executor
    return wrapped(*args, **kwargs)
  File "/data/bkee/bknodeman/nodeman/apps/backend/components/collections/base.py", line 417, in execute
    return self.run(self._execute, data, parent_data, common_data=common_data)
  File "/data/bkee/bknodeman/nodeman/apps/backend/components/collections/base.py", line 334, in run
    service_func(data, parent_data, **kwargs)
  File "/data/bkee/bknodeman/nodeman/apps/backend/components/collections/agent_new/query_password.py", line 78, in _execute
    oa_ticket = host.identity.extra_data.get("oa_ticket")
AttributeError: 'NoneType' object has no attribute 'get'

******** End of collected logs *********
```

**请提供以下信息**

 - [x] bk-nodeman   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk-nodeman 异常日志：

**Comment by donallin823** [comment]
我这边也是手动安装会有很多莫名的NoneType，那等官方的dockerfile出来吗？
